# Generated by Django 4.1.13 on 2025-10-30 09:36

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=255)),
                ('sender_id', models.IntegerField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_id', models.IntegerField(blank=True, null=True)),
                ('deleted_by_name', models.CharField(blank=True, max_length=255)),
                ('attachment', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('room_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('course', 'Course'), ('group', 'Group')], default='public', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by_id', models.IntegerField()),
                ('created_by_email', models.EmailField(max_length=254)),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('participant_ids', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('unread_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chat_participants',
                'unique_together': {('room_id', 'user_id')},
            },
        ),
    ]
