# Generated by Django 5.2.7 on 2025-10-30 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scheduled_date', models.DateTimeField(verbose_name='Date et heure prévue')),
                ('duration', models.IntegerField(default=60, help_text='Durée estimée en minutes', verbose_name='Durée (minutes)')),
                ('meeting_link', models.URLField(blank=True, help_text='Lien Zoom, Jitsi, Google Meet, etc.', max_length=500, verbose_name='Lien de la réunion')),
                ('meeting_id', models.CharField(blank=True, help_text='ID unique pour Jitsi/Zoom', max_length=100, verbose_name='ID de réunion')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarrée le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('attended', 'Présent'), ('absent', 'Absent')], default='invited', max_length=20, verbose_name='Statut')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejoint le')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Quitté le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Réunion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('meeting', 'student')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(related_name='invited_meetings', through='meetings.MeetingParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Étudiants'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['instructor', 'status'], name='meetings_me_instruc_72ca36_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_date'], name='meetings_me_schedul_293aef_idx'),
        ),
    ]
